### PR TITLE
Add an output-chain, needed for proxy-mode=ipvs

### LINKED ISSUE #46: Doesn't work with proxy-mode=ipvs
Reproduce by setting proxy-mode=ipvs and run e2e. Example:

With proxy-mode=iptables (or nftables):
```
export FOCUS="\[sig-network\].*enforce.policy.based.on.PodSelector.with.MatchExpressions.*\[Feature:NetworkPolicy\].*"
# (run e2e)
Ran 1 of 6652 Specs in 9.191 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 6651 Skipped
PASS
```

Same with proxy-mode=ipvs:
```
  I0630 16:31:00.978005 207680 reachability.go:180] expected:

  -             netpol-x-6644/a netpol-x-6644/b netpol-x-6644/c netpol-y-7770/a netpol-y-7770/b netpol-y-7770/c netpol-z-2789/a netpol-z-2789/b netpol-z-2789/c
  netpol-x-6644/a       X               .               .               .               .               .               .               .               .
  netpol-x-6644/b       .               .               .               .               .               .               .               .               .
  netpol-x-6644/c       X               .               .               .               .               .               .               .               .
  netpol-y-7770/a       X               .               .               .               .               .               .               .               .
  netpol-y-7770/b       X               .               .               .               .               .               .               .               .
  netpol-y-7770/c       X               .               .               .               .               .               .               .               .
  netpol-z-2789/a       X               .               .               .               .               .               .               .               .
  netpol-z-2789/b       X               .               .               .               .               .               .               .               .
  netpol-z-2789/c       X               .               .               .               .               .               .               .               .



  I0630 16:31:00.978023 207680 reachability.go:183] observed:

  -             netpol-x-6644/a netpol-x-6644/b netpol-x-6644/c netpol-y-7770/a netpol-y-7770/b netpol-y-7770/c netpol-z-2789/a netpol-z-2789/b netpol-z-2789/c
  netpol-x-6644/a       .               .               .               .               .               .               .               .               .
  netpol-x-6644/b       .               .               .               .               .               .               .               .               .
  netpol-x-6644/c       X               .               .               .               .               .               .               .               .
  netpol-y-7770/a       X               .               .               .               .               .               .               .               .
  netpol-y-7770/b       .               .               .               .               .               .               .               .               .
  netpol-y-7770/c       X               .               .               .               .               .               .               .               .
  netpol-z-2789/a       X               .               .               .               .               .               .               .               .
  netpol-z-2789/b       X               .               .               .               .               .               .               .               .
  netpol-z-2789/c       .               .               .               .               .               .               .               .               .



  I0630 16:31:00.978037 207680 reachability.go:186] comparison:

  -             netpol-x-6644/a netpol-x-6644/b netpol-x-6644/c netpol-y-7770/a netpol-y-7770/b netpol-y-7770/c netpol-z-2789/a netpol-z-2789/b netpol-z-2789/c
  netpol-x-6644/a       X               .               .               .               .               .               .               .               .
  netpol-x-6644/b       .               .               .               .               .               .               .               .               .
  netpol-x-6644/c       .               .               .               .               .               .               .               .               .
  netpol-y-7770/a       .               .               .               .               .               .               .               .               .
  netpol-y-7770/b       X               .               .               .               .               .               .               .               .
  netpol-y-7770/c       .               .               .               .               .               .               .               .               .
  netpol-z-2789/a       .               .               .               .               .               .               .               .               .
  netpol-z-2789/b       .               .               .               .               .               .               .               .               .
  netpol-z-2789/c       X               .               .               .               .               .               .               .               .
```

If `kube-network-policies` is only for K8s testing, this is probably fine, but should be documented.

### PR DESCRIPTION
**Pull request by uablrek**
If the receiving pod is local, then ipvs sends packet via the output hook (not forward). So both are needed

Fixes #46 

Example: 
```
# nft list table inet kube-network-policies
table inet kube-network-policies {
        comment "rules for kubernetes NetworkPolicy"
        set podips-v4 {
                type ipv4_addr
                comment "Local V4 Pod IPs with Network Policies"
                elements = { 11.0.2.2, 11.0.2.3,
                             11.0.2.4 }
        }

        set podips-v6 {
                type ipv6_addr
                comment "Local V6 Pod IPs with Network Policies"
                elements = { 1100::202,
                             1100::203,
                             1100::204 }
        }

        chain forward {
                type filter hook forward priority filter - 5; policy accept;
                ct state established,related accept
                ip saddr @podips-v4 queue to 100 comment "process IPv4 traffic with network policy enforcement"
                ip daddr @podips-v4 queue to 100 comment "process IPv4 traffic with network policy enforcement"
                ip6 saddr @podips-v6 queue to 100 comment "process IPv6 traffic with network policy enforcement"
                ip6 daddr @podips-v6 queue to 100 comment "process IPv6 traffic with network policy enforcement"
        }

        chain output {
                type filter hook output priority filter - 5; policy accept;
                ct state established,related accept
                ip saddr @podips-v4 queue to 100 comment "process IPv4 traffic with network policy enforcement"
                ip daddr @podips-v4 queue to 100 comment "process IPv4 traffic with network policy enforcement"
                ip6 saddr @podips-v6 queue to 100 comment "process IPv6 traffic with network policy enforcement"
                ip6 daddr @podips-v6 queue to 100 comment "process IPv6 traffic with network policy enforcement"
        }
}
```
The "chain output" is added by this PR.

Please see issue #46 for more info

### CODE REVIEW

**Comment by aojea** [comment]
/approve

I think this is ok, but let's wait if Dan have time for review

**Comment by danwinship** [comment]
"NPA" seems to mean "AdminNetworkPolicy"
Only the IPv6 run failed... let's see if it fails if we run it again

**Comment by danwinship** [comment]
/lgtm
other than the test failure; I believe Antonio and I had debated forward-only vs forward-and-output earlier...

**Comment by aojea** [comment]
hmm, it passed in the other CI https://github.com/kubernetes-sigs/network-policy-api/actions/runs/9740745124/job/26878488301

**Comment by uablrek** [comment]
Yeah, and failed 3 times with this PR. There is a link in the log to https://github.com/kubernetes-sigs/network-policy-api.
Perhaps @astoycos has any lead?

**Comment by aojea** [comment]
it has to be this PR then

**Comment by aojea** [comment]
> 2024-07-01T12:51:17.425650028Z stderr F I0701 12:51:17.425622       1 controller.go:390] Processing sync for packet 1783
> 2024-07-01T12:51:17.425660467Z stderr F I0701 12:51:17.425629       1 controller.go:394] Can not process packet 1783 applying default policy (failOpen: false): unknown protocol 58

it seems is blocking icmpv6 because does not recognize it

It seems that is better to just log and let the packet pass through rather than applying the default policy, if is not a protocol that is supported by the network policy APIs blocking them can cause issues, @uablrek can you append a commit to comment this and set the verdict to accept if parsePacket fails?

https://github.com/kubernetes-sigs/kube-network-policies/blob/db089bc6ed6c17a654ef0ea3f3a93d9122041c4e/pkg/networkpolicy/controller.go#L392-L396

**Comment by aojea** [comment]
hmm @BenTheElder points there are new changes on docker , another possible reason https://docs.docker.com/engine/release-notes/27.0/#ipv6

**Comment by BenTheElder** [comment]
We just picked up docker v27.x in CI recently, see the thread here https://github.com/kubernetes-sigs/kind/issues/3677 and https://github.com/kubernetes/test-infra/pull/32863#issuecomment-2201272818

Docker v27 has some behavior changes for ipv6.

**Comment by uablrek** [comment]
>  @uablrek can you append a commit to comment this and set the verdict to accept if parsePacket fails?

Sure

**Comment by uablrek** [comment]
It may be better to extend `parsePacket()`. I have intended to do that (https://github.com/kubernetes-sigs/kube-network-policies/issues/15), but haven't got around to do it yet

**Comment by aojea** [comment]
ok, progressing, different error now??

```
    helper.go:123: StatefulSet replicas in namespace network-policy-conformance-forbidden-forrest not rolled out yet. 1/2 replicas are available.
    helper.go:120: Error retrieving StatefulSet harry-potter from namespace network-policy-conformance-gryffindor: client rate limiter Wait returned an error: context deadline exceeded
    helper.go:123: StatefulSet replicas in namespace network-policy-conformance-gryffindor not rolled out yet. 0/2 replicas are available.
    suite.go:143: 
```

**Comment by uablrek** [comment]
This time the error seem unreated to the PR. How can allowing icmp make a StatefulSet fail to start??

**Comment by aojea** [comment]
> This time the error seem unreated to the PR. How can allowing icmp make a StatefulSet fail to start??

the failure has to be related to the output rule we just added, it does not fail in https://github.com/kubernetes-sigs/kube-network-policies/pull/49

**Comment by aojea** [comment]
@uablrek please leave only first and  last commit,

**Comment by uablrek** [comment]
> @uablrek please leave only first and last commit

@aojea Done. But tests fail. I can't see why.

**Comment by aojea** [comment]
interesting, anyway, this is the part we need to debug and troubleshoot

**Comment by aojea** [comment]
Once we get this sorted out I cut a new release so we can get this into kindnet

**Comment by aojea** [comment]
@uablrek can you rebase?

**Comment by aojea** [comment]
I see, so the problem most likely was that blocking unknown protocols we were blocking icmp, that in IPv6 is needed for discovery ... that may be the reason why adding `lo` to the rules made the test pass

**Comment by uablrek** [comment]
@aojea This can be closed, right?

**Comment by aojea** [comment]
yes

**Comment by aojea** [comment]
we also have coverage now in CI for IPVS to avoid regressions

**Pull request closed without merging**
